name: Build Platform Target

on:
  workflow_dispatch:
  repository_dispatch:
    types: ['build-ready']
  push:
    branches: ['main']
    tags:
      - '**'

env:
  ITCH_IO_PUBLISH: 'true'
  # Set ITCH_IO_API_KEY in Repository Secrets

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      TAG_PUSH: ${{ steps.setenv.outputs.TAG_PUSH }}
      PRERELEASE: ${{ steps.setenv.outputs.PRERELEASE }}
      GIT_TAG: ${{ steps.setenv.outputs.GIT_TAG }}
      ITCH_IO_PUBLISH: ${{ steps.setenv.outputs.ITCH_IO_PUBLISH }}
      TAG_NAME: ${{ steps.tag.outputs.TAG_NAME }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: 'true'

      - name: Set env
        id: setenv
        run: |
          echo "Github Action Event: ${{ github.event_name }}"

          # If HEAD commit contains tag, event is tag push or manual workflow dispatch rerun
          if [ -n "$(git tag -l --contains HEAD)" ] && \
             [ ${{ github.event_name }} != "repository_dispatch" ]; then \
            echo "Tagged Release"; \
            TAG_PUSH=true; \
            PRERELEASE=false; \
          else \
            echo "Rolling Release"; \
            TAG_PUSH=false; \
            PRERELEASE=true; \
          fi

          GIT_TAG="$( git describe --tags --abbrev=0 )"
          GIT_TAG=${GIT_TAG:=0.0.1}

          echo "TAG_PUSH=${TAG_PUSH}" >> $GITHUB_OUTPUT
          echo "PRERELEASE=${PRERELEASE}" >> $GITHUB_OUTPUT
          echo "GIT_TAG=${GIT_TAG}" >> $GITHUB_OUTPUT

          echo "ITCH_IO_PUBLISH=${{ env.ITCH_IO_PUBLISH }}" >> $GITHUB_OUTPUT
          
      - name: Fetch docker action
        id: fetch-action
        run: |
          git clone --branch feat/rx https://github.com/V-Sekai-fire/v-sekai-game.git

      - name: Docker build project
        id: docker
        uses: ./v-sekai-game/docker/build-project
        with:
          repo: ${{ github.repository }}
          nightly: ${{ steps.setenv.outputs.PRERELEASE }}
          default_export: true

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: v-sekai-release
          path: ${{ github.workspace }}/releases

      - name: Set tag name
        id: tag
        run: |
          TAG_NAME="$( echo "${{ steps.docker.outputs.VERSION_TAG }}" | cut -d '-' -f1 )"

          # Rolling release tag
          if [ ${{ steps.setenv.outputs.TAG_PUSH }} == "false" ]; then \
            TAG_DATE="$( date +"%Y-%m-%dT%H%M%S" )"; \
            TAG_VERSION="$( echo "${{ steps.docker.outputs.VERSION_TAG }}" | cut -d '-' -f2- )"; \
            TAG_NAME="${TAG_NAME}-nightly-${TAG_DATE}-${TAG_VERSION}"; \
          fi

          echo "TAG_NAME=${TAG_NAME}" >> $GITHUB_OUTPUT

